#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

init:
  tofu init

test:
  tofu test

plan:
  tofu plan

apply:
  tofu apply

destroy:
  tofu destroy

