#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true
export terraform_extra_args := ""

# default lists actions
default:
  @just -f justfile --list

init:
  terraform init

test:
  terraform test ${terraform_extra_args}

plan:
  terraform plan --var-file=terraform.tfvars 

apply:
  terraform apply --var-file=terraform.tfvars 

destroy:
  terraform destroy --var-file=terraform.tfvars 

