#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

deployed environment="../../../.env":
  #!/usr/bin/env bash
  set -eufo pipefail

  export GOOGLE_APPLICATION_CREDENTIALS="../../../terraform-sa.json"
  ./deployment.py --deployed