name: CI

on:
  push:
    branches: 
      - '*'
      # - '!master'   # excludes main
    paths:
      - '**'
      - '.github/workflows/ci.yaml'

  pull_request:
    branches:  
      - '*'
      # - '!master'   # excludes main
    paths:
      - '**'
      - '.github/workflows/ci.yaml'



jobs:
  github-info:
    runs-on: ubuntu-latest
    name: Github execution information
    steps:
      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump docker info
        run: docker info
      - name: Terraform Version
        run: terraform version  

  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    strategy:
      fail-fast: false
      matrix:
        projects: [
          { project: "01_s3_bucket", tfvars: "01_s3_bucket/terraform.tfvars" },
          { project: "02_asg", tfvars: "02_asg/terraform.tfvars" },
          { project: "03_locks_versions", tfvars: "" },
          { project: "04_envvars", tfvars: "" },
          { project: "05_debugging", tfvars: "" },
          { project: "06_processing_plan_files", tfvars: "06_processing_plan_files/terraform.tfvars" },
          { project: "07_remote_state/create_template_file", tfvars: "" },
          { project: "07_remote_state/render_template_file", tfvars: "" },
          { project: "08_module", tfvars: "" },
          { project: "09_targeting_resources", tfvars: "" },
          { project: "10_workspaces", tfvars: "" },
          { project: "11_importing_state", tfvars: "" },
          { project: "12_upgrading_providers", tfvars: "" },
          { project: "12_upgrading_terraform", tfvars: "" }, 
          { project: "13_importing_data", tfvars: "" },      
          { project: "15_importing_webservice", tfvars: "" },
          { project: "18_terraformer", tfvars: "" },    
          { project: "19_sops", tfvars: "" },
          { project: "20_cdk", tfvars: "" },
          { project: "21_importing_ssm", tfvars: "" },
          { project: "22_drift_detection", tfvars: "" },
          { project: "23_honeycomb", tfvars: "" },
          { project: "24_quine", tfvars: "24_quine/terraform.tfvars" },
          { project: "25_moved", tfvars: "25_moved/terraform.tfvars" },
          { project: "26_github_modules", tfvars: "" },
          { project: "28_aiven_kafka", tfvars: "28_aiven_kafka/terraform.tfvars" },
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate ${{ matrix.projects.project }}
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.projects.project }}

      - name: terraform fmt ${{ matrix.projects.project }}
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.projects.project }}

      - name: terraform plan ${{ matrix.projects.project }}
        uses: dflook/terraform-plan@v1
        with:
          path: ${{ matrix.projects.project }}
          var_file: ${{ matrix.projects.tfvars }}

  semgrep:
    runs-on: ubuntu-latest
    name: Semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: semgrep-action
        uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            r/generic.dockerfile
            r/bash
            p/terraform
            p/typescript
            p/github-actions
            r/html.best-practice.robots-denied.robots-denied
            r/html.security.missing-noopener.missing-noopener
            r/html.security.missing-noreferrer.missing-noreferrer
          



