name: CI

on:
  push:
    branches: 
      - '*'
      # - '!master'   # excludes main
    paths:
      - '**'
      - '.github/workflows/ci.yaml'

  pull_request:
    branches:  
      - '*'
      # - '!master'   # excludes main
    paths:
      - '**'
      - '.github/workflows/ci.yaml'



jobs:
  github-info:
    runs-on: ubuntu-latest
    name: Github execution information
    steps:
      # - name: Dump GitHub context
      #   id: github_context_step
      #   run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump docker info
        run: docker info
      - name: Terraform Version
        run: terraform version  

  validate:
    runs-on: ubuntu-latest
    name: Validate terraform configuration
    strategy:
      fail-fast: false
      matrix:
        projects: [
          "01_s3_bucket",
          "02_asg",
          "03_locks_versions",
          "04_envvars",
          "05_debugging",
          "06_processing_plan_files",
          "07_remote_state",
          "08_module",
          "09_targeting_resources",
          "10_workspaces",
          "11_importing_state",
          "12_upgrading_providers",
          "12_upgrading_terraform", 
          "13_importing_data",      
          "15_importing_webservice",
          "18_terraformer",    
          "19_sops",
          "20_cdk",
          "21_importing_ssm",
          "22_drift_detection",
          "23_honeycomb",
          "24_quine",
          "25_moved",
          "26_github_modules",
          "28_aiven_kafka",
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: ${{ matrix.projects }}

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ${{ matrix.projects }}

      - name: terraform plan
        uses: dflook/terraform-plan@v1
        with:
          path: ${{ matrix.projects }}

  semgrep:
    runs-on: ubuntu-latest
    name: Semgrep
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: semgrep-action
        uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            r/generic.dockerfile
            r/bash
            p/terraform
            p/typescript
            p/github-actions
            r/html.best-practice.robots-denied.robots-denied
            r/html.security.missing-noopener.missing-noopener
            r/html.security.missing-noreferrer.missing-noreferrer
          



