#!/usr/bin/env just --justfile
# ^ A shebang isn't required, but allows a justfile to be executed
#   like a script, with `./justfile test`, for example.

set dotenv-load := true

# default lists actions
default:
  @just -f justfile --list

init:
  terraform init

plan:
  terraform plan

apply *FLAGS:
  terraform apply {{FLAGS}}

destroy:
  terraform destroy

clean:
  rm -rf .terraform
  rm -rf output
  rm -rf state

